 
using System.ComponentModel;

namespace FluentBootstrap
{
	public enum Icon
	{
		[Description("glyphicon-asterisk")]
		Asterisk,
		[Description("glyphicon-plus")]
		Plus,
		[Description("glyphicon-eur")]
		Eur,
		[Description("glyphicon-minus")]
		Minus,
		[Description("glyphicon-cloud")]
		Cloud,
		[Description("glyphicon-envelope")]
		Envelope,
		[Description("glyphicon-pencil")]
		Pencil,
		[Description("glyphicon-glass")]
		Glass,
		[Description("glyphicon-music")]
		Music,
		[Description("glyphicon-search")]
		Search,
		[Description("glyphicon-heart")]
		Heart,
		[Description("glyphicon-star")]
		Star,
		[Description("glyphicon-star-empty")]
		StarEmpty,
		[Description("glyphicon-user")]
		User,
		[Description("glyphicon-film")]
		Film,
		[Description("glyphicon-th-large")]
		ThLarge,
		[Description("glyphicon-th")]
		Th,
		[Description("glyphicon-th-list")]
		ThList,
		[Description("glyphicon-ok")]
		Ok,
		[Description("glyphicon-remove")]
		Remove,
		[Description("glyphicon-zoom-in")]
		ZoomIn,
		[Description("glyphicon-zoom-out")]
		ZoomOut,
		[Description("glyphicon-off")]
		Off,
		[Description("glyphicon-signal")]
		Signal,
		[Description("glyphicon-cog")]
		Cog,
		[Description("glyphicon-trash")]
		Trash,
		[Description("glyphicon-home")]
		Home,
		[Description("glyphicon-file")]
		File,
		[Description("glyphicon-time")]
		Time,
		[Description("glyphicon-road")]
		Road,
		[Description("glyphicon-download-alt")]
		DownloadAlt,
		[Description("glyphicon-download")]
		Download,
		[Description("glyphicon-upload")]
		Upload,
		[Description("glyphicon-inbox")]
		Inbox,
		[Description("glyphicon-play-circle")]
		PlayCircle,
		[Description("glyphicon-repeat")]
		Repeat,
		[Description("glyphicon-refresh")]
		Refresh,
		[Description("glyphicon-list-alt")]
		ListAlt,
		[Description("glyphicon-lock")]
		Lock,
		[Description("glyphicon-flag")]
		Flag,
		[Description("glyphicon-headphones")]
		Headphones,
		[Description("glyphicon-volume-off")]
		VolumeOff,
		[Description("glyphicon-volume-down")]
		VolumeDown,
		[Description("glyphicon-volume-up")]
		VolumeUp,
		[Description("glyphicon-qrcode")]
		Qrcode,
		[Description("glyphicon-barcode")]
		Barcode,
		[Description("glyphicon-tag")]
		Tag,
		[Description("glyphicon-tags")]
		Tags,
		[Description("glyphicon-book")]
		Book,
		[Description("glyphicon-bookmark")]
		Bookmark,
		[Description("glyphicon-print")]
		Print,
		[Description("glyphicon-camera")]
		Camera,
		[Description("glyphicon-font")]
		Font,
		[Description("glyphicon-bold")]
		Bold,
		[Description("glyphicon-italic")]
		Italic,
		[Description("glyphicon-text-height")]
		TextHeight,
		[Description("glyphicon-text-width")]
		TextWidth,
		[Description("glyphicon-align-left")]
		AlignLeft,
		[Description("glyphicon-align-center")]
		AlignCenter,
		[Description("glyphicon-align-right")]
		AlignRight,
		[Description("glyphicon-align-justify")]
		AlignJustify,
		[Description("glyphicon-list")]
		List,
		[Description("glyphicon-indent-left")]
		IndentLeft,
		[Description("glyphicon-indent-right")]
		IndentRight,
		[Description("glyphicon-facetime-video")]
		FacetimeVideo,
		[Description("glyphicon-picture")]
		Picture,
		[Description("glyphicon-map-marker")]
		MapMarker,
		[Description("glyphicon-adjust")]
		Adjust,
		[Description("glyphicon-tint")]
		Tint,
		[Description("glyphicon-edit")]
		Edit,
		[Description("glyphicon-share")]
		Share,
		[Description("glyphicon-check")]
		Check,
		[Description("glyphicon-move")]
		Move,
		[Description("glyphicon-step-backward")]
		StepBackward,
		[Description("glyphicon-fast-backward")]
		FastBackward,
		[Description("glyphicon-backward")]
		Backward,
		[Description("glyphicon-play")]
		Play,
		[Description("glyphicon-pause")]
		Pause,
		[Description("glyphicon-stop")]
		Stop,
		[Description("glyphicon-forward")]
		Forward,
		[Description("glyphicon-fast-forward")]
		FastForward,
		[Description("glyphicon-step-forward")]
		StepForward,
		[Description("glyphicon-eject")]
		Eject,
		[Description("glyphicon-chevron-left")]
		ChevronLeft,
		[Description("glyphicon-chevron-right")]
		ChevronRight,
		[Description("glyphicon-plus-sign")]
		PlusSign,
		[Description("glyphicon-minus-sign")]
		MinusSign,
		[Description("glyphicon-remove-sign")]
		RemoveSign,
		[Description("glyphicon-ok-sign")]
		OkSign,
		[Description("glyphicon-question-sign")]
		QuestionSign,
		[Description("glyphicon-info-sign")]
		InfoSign,
		[Description("glyphicon-screenshot")]
		Screenshot,
		[Description("glyphicon-remove-circle")]
		RemoveCircle,
		[Description("glyphicon-ok-circle")]
		OkCircle,
		[Description("glyphicon-ban-circle")]
		BanCircle,
		[Description("glyphicon-arrow-left")]
		ArrowLeft,
		[Description("glyphicon-arrow-right")]
		ArrowRight,
		[Description("glyphicon-arrow-up")]
		ArrowUp,
		[Description("glyphicon-arrow-down")]
		ArrowDown,
		[Description("glyphicon-share-alt")]
		ShareAlt,
		[Description("glyphicon-resize-full")]
		ResizeFull,
		[Description("glyphicon-resize-small")]
		ResizeSmall,
		[Description("glyphicon-exclamation-sign")]
		ExclamationSign,
		[Description("glyphicon-gift")]
		Gift,
		[Description("glyphicon-leaf")]
		Leaf,
		[Description("glyphicon-fire")]
		Fire,
		[Description("glyphicon-eye-open")]
		EyeOpen,
		[Description("glyphicon-eye-close")]
		EyeClose,
		[Description("glyphicon-warning-sign")]
		WarningSign,
		[Description("glyphicon-plane")]
		Plane,
		[Description("glyphicon-calendar")]
		Calendar,
		[Description("glyphicon-random")]
		Random,
		[Description("glyphicon-comment")]
		Comment,
		[Description("glyphicon-magnet")]
		Magnet,
		[Description("glyphicon-chevron-up")]
		ChevronUp,
		[Description("glyphicon-chevron-down")]
		ChevronDown,
		[Description("glyphicon-retweet")]
		Retweet,
		[Description("glyphicon-shopping-cart")]
		ShoppingCart,
		[Description("glyphicon-folder-close")]
		FolderClose,
		[Description("glyphicon-folder-open")]
		FolderOpen,
		[Description("glyphicon-resize-vertical")]
		ResizeVertical,
		[Description("glyphicon-resize-horizontal")]
		ResizeHorizontal,
		[Description("glyphicon-hdd")]
		Hdd,
		[Description("glyphicon-bullhorn")]
		Bullhorn,
		[Description("glyphicon-bell")]
		Bell,
		[Description("glyphicon-certificate")]
		Certificate,
		[Description("glyphicon-thumbs-up")]
		ThumbsUp,
		[Description("glyphicon-thumbs-down")]
		ThumbsDown,
		[Description("glyphicon-hand-right")]
		HandRight,
		[Description("glyphicon-hand-left")]
		HandLeft,
		[Description("glyphicon-hand-up")]
		HandUp,
		[Description("glyphicon-hand-down")]
		HandDown,
		[Description("glyphicon-circle-arrow-right")]
		CircleArrowRight,
		[Description("glyphicon-circle-arrow-left")]
		CircleArrowLeft,
		[Description("glyphicon-circle-arrow-up")]
		CircleArrowUp,
		[Description("glyphicon-circle-arrow-down")]
		CircleArrowDown,
		[Description("glyphicon-globe")]
		Globe,
		[Description("glyphicon-wrench")]
		Wrench,
		[Description("glyphicon-tasks")]
		Tasks,
		[Description("glyphicon-filter")]
		Filter,
		[Description("glyphicon-briefcase")]
		Briefcase,
		[Description("glyphicon-fullscreen")]
		Fullscreen,
		[Description("glyphicon-dashboard")]
		Dashboard,
		[Description("glyphicon-paperclip")]
		Paperclip,
		[Description("glyphicon-heart-empty")]
		HeartEmpty,
		[Description("glyphicon-link")]
		Link,
		[Description("glyphicon-phone")]
		Phone,
		[Description("glyphicon-pushpin")]
		Pushpin,
		[Description("glyphicon-usd")]
		Usd,
		[Description("glyphicon-gbp")]
		Gbp,
		[Description("glyphicon-sort")]
		Sort,
		[Description("glyphicon-sort-by-alphabet")]
		SortByAlphabet,
		[Description("glyphicon-sort-by-alphabet-alt")]
		SortByAlphabetAlt,
		[Description("glyphicon-sort-by-order")]
		SortByOrder,
		[Description("glyphicon-sort-by-order-alt")]
		SortByOrderAlt,
		[Description("glyphicon-sort-by-attributes")]
		SortByAttributes,
		[Description("glyphicon-sort-by-attributes-alt")]
		SortByAttributesAlt,
		[Description("glyphicon-unchecked")]
		Unchecked,
		[Description("glyphicon-expand")]
		Expand,
		[Description("glyphicon-collapse-down")]
		CollapseDown,
		[Description("glyphicon-collapse-up")]
		CollapseUp,
		[Description("glyphicon-log-in")]
		LogIn,
		[Description("glyphicon-flash")]
		Flash,
		[Description("glyphicon-log-out")]
		LogOut,
		[Description("glyphicon-new-window")]
		NewWindow,
		[Description("glyphicon-record")]
		Record,
		[Description("glyphicon-save")]
		Save,
		[Description("glyphicon-open")]
		Open,
		[Description("glyphicon-saved")]
		Saved,
		[Description("glyphicon-import")]
		Import,
		[Description("glyphicon-export")]
		Export,
		[Description("glyphicon-send")]
		Send,
		[Description("glyphicon-floppy-disk")]
		FloppyDisk,
		[Description("glyphicon-floppy-saved")]
		FloppySaved,
		[Description("glyphicon-floppy-remove")]
		FloppyRemove,
		[Description("glyphicon-floppy-save")]
		FloppySave,
		[Description("glyphicon-floppy-open")]
		FloppyOpen,
		[Description("glyphicon-credit-card")]
		CreditCard,
		[Description("glyphicon-transfer")]
		Transfer,
		[Description("glyphicon-cutlery")]
		Cutlery,
		[Description("glyphicon-header")]
		Header,
		[Description("glyphicon-compressed")]
		Compressed,
		[Description("glyphicon-earphone")]
		Earphone,
		[Description("glyphicon-phone-alt")]
		PhoneAlt,
		[Description("glyphicon-tower")]
		Tower,
		[Description("glyphicon-stats")]
		Stats,
		[Description("glyphicon-sd-video")]
		SdVideo,
		[Description("glyphicon-hd-video")]
		HdVideo,
		[Description("glyphicon-subtitles")]
		Subtitles,
		[Description("glyphicon-sound-stereo")]
		SoundStereo,
		[Description("glyphicon-sound-dolby")]
		SoundDolby,
		[Description("glyphicon-sound-5-1")]
		Sound_5_1,
		[Description("glyphicon-sound-6-1")]
		Sound_6_1,
		[Description("glyphicon-sound-7-1")]
		Sound_7_1,
		[Description("glyphicon-copyright-mark")]
		CopyrightMark,
		[Description("glyphicon-registration-mark")]
		RegistrationMark,
		[Description("glyphicon-cloud-download")]
		CloudDownload,
		[Description("glyphicon-cloud-upload")]
		CloudUpload,
		[Description("glyphicon-tree-conifer")]
		TreeConifer,
		[Description("glyphicon-tree-deciduous")]
		TreeDeciduous,
		[Description("glyphicon-cd")]
		Cd,
		[Description("glyphicon-save-file")]
		SaveFile,
		[Description("glyphicon-open-file")]
		OpenFile,
		[Description("glyphicon-level-up")]
		LevelUp,
		[Description("glyphicon-copy")]
		Copy,
		[Description("glyphicon-paste")]
		Paste,
		[Description("glyphicon-alert")]
		Alert,
		[Description("glyphicon-equalizer")]
		Equalizer,
		[Description("glyphicon-king")]
		King,
		[Description("glyphicon-queen")]
		Queen,
		[Description("glyphicon-pawn")]
		Pawn,
		[Description("glyphicon-bishop")]
		Bishop,
		[Description("glyphicon-knight")]
		Knight,
		[Description("glyphicon-baby-formula")]
		BabyFormula,
		[Description("glyphicon-tent")]
		Tent,
		[Description("glyphicon-blackboard")]
		Blackboard,
		[Description("glyphicon-bed")]
		Bed,
		[Description("glyphicon-apple")]
		Apple,
		[Description("glyphicon-erase")]
		Erase,
		[Description("glyphicon-hourglass")]
		Hourglass,
		[Description("glyphicon-lamp")]
		Lamp,
		[Description("glyphicon-duplicate")]
		Duplicate,
		[Description("glyphicon-piggy-bank")]
		PiggyBank,
		[Description("glyphicon-scissors")]
		Scissors,
		[Description("glyphicon-bitcoin")]
		Bitcoin,
		[Description("glyphicon-btc")]
		Btc,
		[Description("glyphicon-xbt")]
		Xbt,
		[Description("glyphicon-yen")]
		Yen,
		[Description("glyphicon-jpy")]
		Jpy,
		[Description("glyphicon-ruble")]
		Ruble,
		[Description("glyphicon-rub")]
		Rub,
		[Description("glyphicon-scale")]
		Scale,
		[Description("glyphicon-ice-lolly")]
		IceLolly,
		[Description("glyphicon-ice-lolly-tasted")]
		IceLollyTasted,
		[Description("glyphicon-education")]
		Education,
		[Description("glyphicon-option-horizontal")]
		OptionHorizontal,
		[Description("glyphicon-option-vertical")]
		OptionVertical,
		[Description("glyphicon-menu-hamburger")]
		MenuHamburger,
		[Description("glyphicon-modal-window")]
		ModalWindow,
		[Description("glyphicon-oil")]
		Oil,
		[Description("glyphicon-grain")]
		Grain,
		[Description("glyphicon-sunglasses")]
		Sunglasses,
		[Description("glyphicon-text-size")]
		TextSize,
		[Description("glyphicon-text-color")]
		TextColor,
		[Description("glyphicon-text-background")]
		TextBackground,
		[Description("glyphicon-object-align-top")]
		ObjectAlignTop,
		[Description("glyphicon-object-align-bottom")]
		ObjectAlignBottom,
		[Description("glyphicon-object-align-horizontal")]
		ObjectAlignHorizontal,
		[Description("glyphicon-object-align-left")]
		ObjectAlignLeft,
		[Description("glyphicon-object-align-vertical")]
		ObjectAlignVertical,
		[Description("glyphicon-object-align-right")]
		ObjectAlignRight,
		[Description("glyphicon-triangle-right")]
		TriangleRight,
		[Description("glyphicon-triangle-left")]
		TriangleLeft,
		[Description("glyphicon-triangle-bottom")]
		TriangleBottom,
		[Description("glyphicon-triangle-top")]
		TriangleTop,
		[Description("glyphicon-console")]
		Console,
		[Description("glyphicon-superscript")]
		Superscript,
		[Description("glyphicon-subscript")]
		Subscript,
		[Description("glyphicon-menu-left")]
		MenuLeft,
		[Description("glyphicon-menu-right")]
		MenuRight,
		[Description("glyphicon-menu-down")]
		MenuDown,
		[Description("glyphicon-menu-up")]
		MenuUp,
		[Description("")]
		None
	}
}
